name: sliding_panel
description: A Flutter slidable widget that provides an easy to use configuration. Just as you want it!
version: 0.1.0
author: Ravi Kavaiya <ravikavaiya3.rk@gmail.com>
homepage: https://github.com/RaviKavaiya/sliding_panel

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
